name: Receiving Build APK Test

on:
  workflow_dispatch:

jobs:
  beta-distribution:
    runs-on: ubuntu-latest
    name: Beta Distribution
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'

    - name: Install Fastlane
      run: |
        bundle install
        bundle update fastlane

    - name: Install node modules
      run: |
        yarn install --ignore-engines

    - name: Make Gradlew Executable
      run: cd android && chmod +x ./gradlew

    - name: Build Android App Bundle
      env:
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: bundle exec fastlane android beta
